export const statFieldsBySport = {
  football: [
    { key: "goals",             label: "Gól" },
    { key: "assists",           label: "Gólpassz" },
    { key: "shots_total",       label: "Lövések összesen" },
    { key: "shots_on_target",   label: "Kaput eltaláló lövés" },
    { key: "fouls_committed",   label: "Szabálytalanság" },
    { key: "yellow_cards",      label: "Sárga lap" },
    { key: "red_cards",         label: "Piros lap" },
    { key: "penalties_taken",   label: "Elvégzett büntető" },
    { key: "penalties_scored",  label: "Belőtt büntető" },
    { key: "offsides",          label: "Les" },
    { key: "corners",           label: "Szögletek" },
    { key: "free_kick",         label: "Szabadrúgások" },
    { key: "throw_ins",         label: "Bedobások" },
    { key: "total_passes",      label: "Passzok összesen" },
    { key: "successful_passes", label: "Sikeres passzok" },
    { key: "interception",      label: "Labdaszerzések" },
    { key: "tackles",           label: "Szerelések" },
    { key: "goalkeeper_saves",  label: "Kapus védések" },
  ],

  basketball: [
    { key: "points_2pt",            label: "2 pontos dobás" },
    { key: "points_3pt",            label: "3 pontos dobás" },
    { key: "assists",               label: "Assziszt" },
    { key: "shots_total",           label: "Dobások összesen" },
    { key: "shots_on_target",       label: "Palánkot talált" },
    { key: "penalties_taken",       label: "Büntetődobások összesen" },
    { key: "penalties_scored",      label: "Bedobott büntetők" },
    { key: "rebounds",              label: "Lepattanó" },
    { key: "interception",          label: "Labdaszerzés" },
    { key: "blocks",                label: "Blokk" },
    { key: "turnovers",             label: "Eladott labda" },
    { key: "personal_fouls",        label: "Személyi hiba" },
    { key: "technical_fouls",       label: "Technikai hiba" },
    { key: "unsportsmanlike_fouls", label: "Sportszerűtlen hiba" },
  ],

  handball: [
    { key: "goals",               label: "Gólok" },
    { key: "assists",             label: "Gólpassz" },
    { key: "shots_total",         label: "Dobások összesen" },
    { key: "shots_on_target",     label: "Kaput eltaláló dobás" },
    { key: "penalties_taken",     label: "Elvégzett hétméteresek" },
    { key: "penalties_scored",    label: "Belőtt hétméteresek" },
    { key: "fouls_committed",     label: "Szabálytalanságok" },
    { key: "free_kick",           label: "Szabaddobások" },
    { key: "interception",        label: "Labdaszerzések" },
    { key: "turnovers",           label: "Eladott labdák" },
    { key: "two_min_suspensions", label: "2 perces kiállítások" },
    { key: "yellow_cards",        label: "Sárga lapok" },
    { key: "red_cards",           label: "Piros lapok" },
    { key: "goalkeeper_saves",    label: "Kapus védések" },
  ],
};
